name: 'Build PR 🧪'

run-name: Build ${{ github.event_name }} ${{ github.event.number }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-code:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency:
      group: ${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        run: echo "building..."

      - name: Wait 2 sec
        run: sleep 2

  dev:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: DEV
    steps:
      - name: Checkout
        run: echo "running dev checks..."      

      - name: Wait 2 sec
        run: sleep 2
  qa:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: QA
    steps:
      - name: Checkout
        run: echo "running qa checks..."     

      - name: Wait 2 sec
        run: sleep 2
  prod:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: PROD
    steps:
      - name: Checkout
        run: echo "running prod checks..."

      - name: Wait 2 sec
        run: sleep 2

