name: 'Build PR 🧪'

run-name: Build ${{ github.event_name }} ${{ github.event.number }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-code:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency:
      group: ${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        run: echo "building..."

  dev:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: DEV
    steps:
      - name: Checkout
        run: echo "running dev checks..."      

  tst:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: TST
    steps:
      - name: Checkout
        run: echo "running qa checks..."     

  acc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: ACC
    steps:
      - name: Checkout
        run: echo "running prod checks..."

  prd:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: PRD
    steps:
      - name: Checkout
        run: echo "running prod checks..."



        