# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Action to perform
        type: choice
        required: true
        options:
          - infra
          - site
          - all
        default: 'site'
      identifier:
        description: Workflow identifier
        type: string

jobs:
  deploy_dev:
    name: 'deploy_dev - ${{ github.event.inputs.identifier }}'
    runs-on: 'ubuntu-latest'
    environment: DEV
    timeout-minutes: 30
    steps:
      - name: Dump event input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github.event.inputs) }}

      - name: Dump github
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github) }}

  deploy_test:
    name: 'deploy_test - ${{ github.event.inputs.identifier }}'
    needs:  deploy_dev
    runs-on: 'ubuntu-latest'
    environment: TST
    timeout-minutes: 30
    steps:
      - name: Dump event input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github.event.inputs) }}

      - name: Dump github
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github) }}

  deploy_qa:
    name: 'deploy_qa - ${{ github.event.inputs.identifier }}'
    needs:  deploy_test
    environment: QA
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - name: Dump event input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github.event.inputs) }}

      - name: Dump github
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github) }}        

  deploy_prod:
    name: 'deploy_prod - ${{ github.event.inputs.identifier }}'
    needs:  deploy_qa
    environment: PROD
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - name: Dump event input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github.event.inputs) }}

      - name: Dump github
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github) }}