name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: choice
        required: true
        options:
          - infra
          - site
          - all
        default: 'site'

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - name: Dump event input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github.event.inputs) }}

      - name: Dump input
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(inputs) }}

      - name: Dump github
        run: echo "$CTX"
        env:
            CTX: ${{ toJson(github) }}            

  job2:
    if: |
      (github.event.inputs.action == 'site' || github.event.inputs.action == 'all') &&
      (!cancelled() && !failure())
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30    
    steps:
      - name: Dump event input
        run: echo Running